DROP TABLE LEGATURA CASCADE CONSTRAINTS;
DROP TABLE COPIL CASCADE CONSTRAINTS;
DROP TABLE UTILIZATOR CASCADE CONSTRAINTS;
DROP TABLE DEVICE CASCADE CONSTRAINTS;
DROP TABLE ZONA CASCADE CONSTRAINTS;
DROP TABLE LEGATURA_ZONA CASCADE CONSTRAINTS;
DROP TABLE ZONA_APROBATA CASCADE CONSTRAINTS;
DROP TABLE ZONA_RISC CASCADE CONSTRAINTS;
